### ISSUE TITLE
Unable to run the app

### ISSUE THREAD

**Issue by demacomsistemas** [aclec/expo-zebra-scanner#14]
What I did:
1) git clone https://github.com/aclec/expo-zebra-scanner.git
2) cd expo-zebra-scanner
3) yarn install
4) yarn add expo
5) npx expo run:android

And this is the error:
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/lili/invapp/expo-zebra-scanner/node_modules/expo/android/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating project ':expo'.
> Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s
5 actionable tasks: 4 executed, 1 from cache
Error: /Users/lili/invapp/expo-zebra-scanner/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
Error: /Users/lili/invapp/expo-zebra-scanner/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/lili/invapp/expo-zebra-scanner/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:635:26)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/Users/lili/invapp/expo-zebra-scanner/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawnGradleAsync (/Users/lili/invapp/expo-zebra-scanner/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:96:48)
    at assembleAsync (/Users/lili/invapp/expo-zebra-scanner/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:74:18)
    at runAndroidAsync (/Users/lili/invapp/expo-zebra-scanner/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:45:37)

**Comment by aclec** [comment]
Hi, it's not an Expo project but an Expo Module project.
It doesn't work like that. If you want to run this project, you need to start 2 terminals:

First terminal:
cd expo-zebra-scanner
yarn
yarn build

Second terminal:
cd expo-zebra-scanner/example
yarn
yarn android

**Comment by demacomsistemas** [comment]
Hi. Thanks for your response. I'm new to react native. Can you explain here what is a "Expo Module project"? I'll try what you mentioned before and let you know

**Comment by aclec** [comment]
Expo has created 'expo-module-core' which allows for the creation of native modules for Expo. In the first part of the repository, there is only the native code along with the tools to build and package it. Then, it can be tested with the accompanying Expo project in the `example` directory.

**Comment by demacomsistemas** [comment]
Thanks again. Followed the indicated steps, but still have some error:
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/lili/invapp/expo-zebra-scanner/node_modules/expo-asset/android/build.gradle' line: 10

* What went wrong:
A problem occurred evaluating project ':expo-asset'.
> Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-asset' of type org.gradle.api.Project.

**Comment by aclec** [comment]
Have you installed all the necessary tools to build native code, including Android Studio and all required SDKs?

**Comment by aclec** [comment]
It sems that could be an error with expo SDK 50.
Upgrade to Expo 51 in the example directory or create an Expo project and add the lib with yarn install.

**Comment by demacomsistemas** [comment]
Upgrade done according https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/
Commands were executed in both expo-zebra-scanner and expo-zebra-scanner/example folders:
yarn add expo@51
npx expo install --fix

Then,
First terminal:
cd expo-zebra-scanner
yarn
yarn build

Second terminal:
cd expo-zebra-scanner/example
yarn
yarn android

And...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:flipper-integration:.
     Required by:
         project :app
   > Could not resolve project :expo-zebra-scanner.
     Required by:
         project :app > project :expo
      > No matching configuration of project :expo-zebra-scanner was found. The consumer was configured to find a library for use during compile-time, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.2.1', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

**Comment by aclec** [comment]
Have you upgraded the SDK in the example directory?
You should change anything in the parent directory

**Comment by demacomsistemas** [comment]
Ok. I've run both commands in both directories... Should I delete everything start from scratch?

**Comment by aclec** [comment]
Yes, but the best way is to create a development build using Expo and add my library with Yarn. Are you sure all the necessary tools are installed to make native code on your computer (SDK, NDK, etc.)?

**Comment by demacomsistemas** [comment]
I think so. Before trying your app, I've wrote my own app with expo. Now I'm trying to add to this app the funcionality to get the barcodes scanned. I'm using a Zebra TC21 device. The app is well installed in the device and everytihing else works fine. Then I added the following lines of code, but handleZebraScanned is never fired...

import * as ExpoZebraScanner from "expo-zebra-scanner";

    useEffect(() => {

      const event = ExpoZebraScanner.addListener(e => {
          const {scanData, scanLabelType} = e;
          handleZebraScanned(scanData);
      });
      //alert('Transferencia.js ExpoZebraScanner.addListener startScan');
      ExpoZebraScanner.startScan();

      return () => {
        //alert('Transferencia.js ExpoZebraScanner.addListener removeListener');
        ExpoZebraScanner.removeListener(event);
        //alert('Transferencia.js ExpoZebraScanner.addListener stopScan');
        ExpoZebraScanner.stopScan();
      }

    },[]);

    function handleZebraScanned (data) {
      console.log(`Transferencia.js handleZebraScanned data=` + data);
      alert(`Transferencia.js handleZebraScanned data=` + data);
    };

**Comment by aclec** [comment]
Have you completed all the DataWedge configuration as I described?

**Comment by demacomsistemas** [comment]
Mmmhhhh... some of them

1) Disable default profile ==> no
2) Create a new profile and allow your app (com.exemple.app) ==> Yes
3) Enable Bardcode ==> No. Can't find where to configure it, but I think it is enabled because a barcode is scanned when a TextInput has focus
4) Enable Intent (with configuration below)  ==> No. Can't find where to configure it. 
    Intent => Broadcast Diffusion
    ACTION => com.symbol.datawedge.ACTION_BARCODE_SCANNED

Can you help me with this?

**Comment by demacomsistemas** [comment]
![WhatsApp Image 2024-07-16 at 12 23 53](https://github.com/user-attachments/assets/531ca32b-b69c-4c15-8e64-2135b2ce124a)

Where can I fill the options you mentioned?
Intent => Broadcast Diffusion
ACTION => com.symbol.datawedge.ACTION_BARCODE_SCANNED

**Comment by aclec** [comment]
It's the DataWedge configuration that sends the data to the app. If you don't set it up, it's normal that it won't work.
You need to disable the default profile because when it is active, DataWedge doesn't use the other profile, and there is a bug.
I've attached a screenshot for the configuration.
![s1](https://github.com/user-attachments/assets/0b834d64-3e9f-40cd-9229-47d4cd8c0a5e)
![s2](https://github.com/user-attachments/assets/a0f8cad9-0c2a-4074-96e3-a05f505e2267)

**Comment by demacomsistemas** [comment]
Nice, thank you so much. I'm receiving the barcode as string. Excellent. Now, when the function handleZebraScanned(scanData) is called, the app is crashing. There is some restrictions here? Or something else to take care of?

Can I add that I've configured to send ENTER key after scanning.

**Comment by aclec** [comment]
Replace ExpoZebraScanner.removeListener(event) with event.remove(). 
Also, you can't run the same listener twice. 
Make sure to start it just once and not in a component with multiple renders, as you can't listen to the same event multiple times simultaneously. 
Place the listener in the parent component.

**Comment by demacomsistemas** [comment]
Ok. But what if I need to call handleZebraScanned(scanData) in more than one component? To be more specific, I've two screens with a BottomTabNavigation. On both screens is required to get the scanned barcode and process it inside the function named handleZebraScanned(scanData)

**Comment by aclec** [comment]
It's not a problem because when you leave the screen and navigate to another using BottomTabNavigation, the cleanup function of useEffect is called (the return statement), which removes the listener. This ensures that there is only one active listener at the same time.
