### ISSUE TITLE
Thank you for working on this

### ISSUE THREAD

**Issue by DaveAldon** [aclec/expo-zebra-scanner#16]
I just wanted to say thanks for putting this library together. It works great for the exact niche I need for working on a Zebra project with Expo. You've saved me a lot of time and headache.

**Comment by aclec** [comment]
Hi,

Thank you for your support!

When I needed it for my application, unfortunately, there was nothing available, which is why I developed this library. 

I need it for my own apps, and I plan to maintain it for future Expo SDKs!
