### ISSUE TITLE
Not working in SDK 52

### ISSUE THREAD

**Issue by daankennes** [aclec/expo-zebra-scanner#21]
Thank you for your work on this module!

I've noticed today that the module does not work anymore after an upgrade to SDK 52. I created a new project afterwards to make sure there was no other problem with my existing app.

Steps to reproduce:
- Create a new Expo app (using the latest SDK, default options)
- Install expo-zebra-scanner
- Create a development build
- I used this code:
```
const createBasicProfile = () => {
    ExpoZebraScanner.createIntentDatawedgeProfile({
        PROFILE_NAME: 'ExpoDatawedgeExample',
        PACKAGE_NAME: 'com.daank.myapp',
    });
};

  useEffect(() => {
    createBasicProfile();
    const listener = ExpoZebraScanner.addListener(event => {
      const { scanData, scanLabelType } = event;
      console.log(scanData);
    });

    ExpoZebraScanner.startScan();

    return () => {
      ExpoZebraScanner.stopScan();
      listener?.remove();
    };
  }, []);
```
- Note that the profile is created, but code data does not get logged

**Comment by aclec** [comment]
Hello,
Expo SDK 52 includes React Native 0.76.
I noticed there are changes related to Expo modules (new architecture and others).

I haven’t updated to SDK 52 yet. This SDK be supported with version 5.0 of expo-zebra-scanner.
It will be available this month.

**Comment by Shadic78** [comment]
Hi @aclec, are you working on this?, the issue is caused by a few lines of code, I already have the patch to work with SDK 52 (old arch, new arch not tested) but if you're already doing something I'll refrain from doing a PR.

**Comment by aclec** [comment]
> Hi @aclec, are you working on this?, the issue is caused by a few lines of code, I already have the patch to work with SDK 52 (old arch, new arch not tested) but if you're already doing something I'll refrain from doing a PR.

Hi, yes I will upload all updates next week
