### ISSUE TITLE
Scanner works in every input filed without call. 

### ISSUE THREAD

**Issue by creen-aps** [aclec/expo-zebra-scanner#9]
Maybe this is not problem, i do not have to add-listener for scanning . All text-input in project can scan codes without any code for zebra scanner.

**Comment by aclec** [comment]
Hi,

The zebra scanner is used as keyboard by default to fill text inputs.
But you need to focus the input before scan.

I'm using this lib to scan QRcodes or Barcodes and then handle custom functions in my code (not to fill text inputs).
